module.exports = {
	USER_CONNECTED: "USER_CONNECTED",
	USER_DISCONNECTED: "USER_DISCONNECTED",
	GAME_UPDATE: "GAME_UPDATE",
	VERIFY_USER: "VERIFY_USER",
	LOGOUT: "LOGOUT",
	USER_READY: "USER_READY",
	GAME_START: "GAME_START",
	GAME_INIT: "GAME_INIT",
	READY: "READY",
	USER_IN_GAME: "USER_IN_GAME",
	GAME_REQUEST: "GAME_REQUEST",
	REQUEST_DENIED: "REQUEST_DENIED",
	RESET: "RESET"
}